[package]
name = "wardrobe-core"
version = "0.26.722"
edition = "2024"
license = "MIT"

[lib]
name = "wardrobe_core"
path = "src/lib.rs"

[dependencies]
rand = "0.10.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.9.12"
bson = "2.13.0"
uuid = { version = "1.0", features = ["v4"] }
tracing = { version = "0.1.44", default-features = false, features = ["std"] }
