[package]
name = "wardrobe-benchmark"
version = "0.26.722"
edition = "2024"

[[bin]]
name = "wardrobe-benchmark"
path = "src/main.rs"

[dependencies]
mongodb = { version = "2.8.2", default-features = false, features = ["sync"] }
mysql = { version = "25.0", default-features = false, features = ["buffer-pool", "minimal", "native-tls"] }
neo4rs = "0.8.0"
rusqlite = { version = "0.32", features = ["bundled"] }
serde_json = "1.0"
tokio = { version = "1", features = ["rt-multi-thread"] }
wardrobe-core = { path = "../../core" }
wardrobe-server = { path = "../../server" }
