[package]
name = "wardrobe-server"
version = "0.26.724"
edition = "2024"
license = "BUSL-1.1"

[[bin]]
name = "wardrobe-server"
path = "src/main.rs"

[dependencies]
serde_json = "1.0"
wardrobe-core = { path = "../core", package = "wardrobe-embedded", version = "0.26.724" }
rustls = { version = "0.23.41", default-features = false, features = ["ring", "std", "tls12"] }
rustls-pemfile = "2.2.0"
