import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const packageJsonPath = resolve(projectRoot, 'package.json');
const versionModulePath = resolve(projectRoot, 'src/app/app-version.ts');

const packageJson = JSON.parse(await readFile(packageJsonPath, 'utf8'));
const version = packageJson.version;

if (typeof version !== 'string' || version.trim() === '') {
  throw new Error('package.json must define a non-empty string version');
}

const generatedSource = `// This file is generated by tools/generate-version.mjs from package.json.\nexport const APP_VERSION = ${JSON.stringify(version)};\n`;

await writeFile(versionModulePath, generatedSource, 'utf8');
