name: Publish Crates

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    environment: crates-environment
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Publish Crates
        run: bash ./utilities/scripts/publish-crates.sh --token "${{ secrets.CARGO_REGISTRY_TOKEN }}"
