name: Publish Crates

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    environment: crates-environment
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Publish wardrobe-client
        run: cargo publish -p wardrobe-client

      - name: Publish wardrobe-embedded
        run: cargo publish -p wardrobe-embedded
